name: app_maxall2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # واجهات آيفون
  cupertino_icons: ^1.0.8

  # مكتبات المشروع
  carousel_slider: ^5.0.0
  http: ^1.3.0
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2 # الإصدار المتوافق الجديد
  image_picker: ^0.8.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - images/               # صور عامة
    - assets/               # لتفادي مشاكل facebook/twitter/google
    - assets/icon/          # أيقونة التطبيق

# إعدادات أيقونة التطبيق
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.jpg"